---
title: "Greg Cooke's CV"
author: Greg Cooke
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    self_contained: false
  knit: pagedown::chrome_print

---

Aside
================================================================================

Contact {#contacts}
--------------------------------------------------------------------------------

<i class="fa fa-linkedin"></i> [gc394](https://www.linkedin.com/in/gc394/)

<i class="fa fa-github"></i> [gc394](https://github.com/gc394)

<i class="fa fa-envelope"></i> greg.cooke98@icloud.com

<i class="fa fa-phone"></i> +44 7917 391 505


Skills {#skills}
--------------------------------------------------------------------------------

**Languages:**

- R (including *Shiny* and *Markdown*)
- Tableau
- SQL
- Python

**Knowledge:**

- Data pipelines
- Dashboards
- Statistical analysis
- Statistical learning models
- Stakeholder management


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Last updated on `r Sys.Date()`

Main
================================================================================

Greg Cooke {#title}
--------------------------------------------------------------------------------

I hold an interest in data science in all forms taking on new projects and experiences with alacrity and focus. This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown)


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Shiplake College

A-levels in Mathematics A\*, Further Mathematics A\*, Economics A, English Literature (AS) A

Henley-on-Thames, Oxfordshire

2011 - 2016

Head boy and all-round scholar

### University of Exeter

BSc Economics with Industrial Experience (Class I)

Exeter, Devon

2016 - 2020

Business School Commendation 2016/2017 & 2019/2020, Eximpact Hackathon Winner (2017), University Colours (2020), Club Captain of the Year (2020)

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data and Statistics, Research Assistant

Bank of England

London, England

2018 - 2019

::: concise
- Created data pipelines
- Taught R for Beginners
- Produced machine-learning models for anomaly detection
:::

### Sustainability and Trading Data Scientist

Spring

London, England

2020 - 2021

::: concise
- Collected and analysed environmental data for reports
- Built ETLs for in-house databases, KPI dashboards and newsletters in Python
- Produced machine-learning models to price items both bought and sold
:::

*Reference on request*

### Data Science Mentor

upGrad

Online

2021 - Present

::: concise
- Teaching fundamental data science skills and Python
- Presenting on various pathways within the industry 
:::

### Data Analyst

Bank of England

London, England

2021 - Present

::: concise
- Producing dashboards in Tableau
- Collaborating with stakeholders to produce bespoke analytical tools
- Building data pipelines in R and SQL
:::
